site_name: 'Example Documentation'
repo_url: https://github.com/rmrosa25/rr_petclinic/
edit_uri: edit/master/plugins/techdocs-backend/examples/documented-component/docs

nav:
  - Home: index.md
  - Subpage: sub-page.md
  - 'Code Sample': code/code-sample.md
  - Extensions: extensions.md

plugins:
  - techdocs-core
